INSERT INTO comments (username, comment, img_id) VALUES 
('Maike','Every year I hope one of them will build a nest on my balcony!',1),
('Lukas','You already had so many birds nest on your balcony - its crazy!',1),
('Mika','Jaaaa, that would be so cute.',1),
('Chris','OMG I love duck eggs. There sooo creamy and yummy!',1),
('Lukas','Ewwwww!',1),
('Kati','I heard they are only pink because they eat so many raspberries!',2),
('Nicky','Noooo, its because of the carotenoid pigments contained in their diet. They eat mostly algae and shrimps!',2),
('Kati','Oh....silly me! hihihihii',2),
('Felix','Oh what a wonderful chicken!',8), 
('Mika','Indeed - love those luscious feathers!',8), 
('Lara','Ohh soo cute - my grandma had a chicken just like that!',8), 
('Mika','I wish I had a chicken like that!',8), 
('Felix','In your small apartment?!?',8), 
('Mika','It could live on the bathroom - hehehee!',8), 
('Lukas','Wowwwww....ive never seen a bird like that!',9),
('Mari','I love the name - sounds super romantic.',9),
('Lisa','I think Ive seen one like that on my balcony once!',9),
('Mari','Really in Berlin?!',9),
('Lukas','I doubt it!',9),
('Lisa','No I swear...! My cat attacked it - it just missed it and the bird got away!',9),
('Anita','Ohh cute - he/she will turn into a beautiful swan one day!',10),
('Scott','Or an evil one. At a school picnic a swan once attacked us and tried to steal our lunch boxes!',10),
('Anita','oh noooo - glad youre still alive!',10),
('Scott','Me too! Im still traumatised!',10),
('Nacho','Storks are evil - If they think their neighbours babies are prettier and healthier than their own, they fly over to the neighbours nest and pierce their babies with their long sharp beaks and oush them off the nest!',11),
('Maike','What? Really? How would give those baby killers the responsibility to deliver human babies?! ',11),
('Nacho','Hahahahaa - idk. Its pretty gruesome and pretty ironic!',11),
('Eili','Woody the Woodpecker - anyone remember that cartoon?',12),
('Nicky','No.',12),
('Cary','No!',12),
('Julie','Noooo, whos dat?!',12),
('Eili','Oh guys - you really missed something!',12),
('Chris','Isnt that the guy with the fruit loops?!',13),
('Michéle','Eww - what are fruit loops?',13), 
('Chris','Yummy, sweet and sticky!',13),
('Michéle','Oh - so like your mom?! LOL',13),
('Chris','You wish your mom was sweet and sticky!',13),
('Nacho','My favourite birds!',14),
('Felix','Why do you like them? Theyre so dirty!',14),
('Nacho','NO, they are actually very social and very clever.',14), 
('Nacho','All ancestors of city pigeons used to be domesticated birds. And then we left them to live on their own.',14),
('Felix','Crows are extremely intelligent birds!',15),
('Maria','Yeah, I heard they can actually recognise human faces and remember them!',15),
('Nicky','Thats sooo scary!',15),
('Paul','Did you know kookaburras sound like laughing monkeys?',16), 
('Bonny','OMG NO! I would love to hear that!',16), 
('Paul','Lets go Oz and go on a kookaburra bush adventure!',16), 
('Cary','Take me with youuuuuu!!',16);